// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi7bzpU4d2mA9mns_91IveIItDd2sEjHA',
    appId: '1:904970774154:android:8a79327102eeb289d56f73',
    messagingSenderId: '904970774154',
    projectId: 'pos-system-47f93',
    databaseURL: 'https://pos-system-47f93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-system-47f93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMSV9CRYCZtNErVlY1r6GQMII-2xwC1xU',
    appId: '1:904970774154:ios:2d0ed4521e5ec354d56f73',
    messagingSenderId: '904970774154',
    projectId: 'pos-system-47f93',
    databaseURL: 'https://pos-system-47f93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-system-47f93.appspot.com',
    iosClientId: '904970774154-gdbhms48bhbcaesqd7j9g0tihibkeg5c.apps.googleusercontent.com',
    iosBundleId: 'com.reso.posApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMSV9CRYCZtNErVlY1r6GQMII-2xwC1xU',
    appId: '1:904970774154:ios:2d0ed4521e5ec354d56f73',
    messagingSenderId: '904970774154',
    projectId: 'pos-system-47f93',
    databaseURL: 'https://pos-system-47f93-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pos-system-47f93.appspot.com',
    iosClientId: '904970774154-gdbhms48bhbcaesqd7j9g0tihibkeg5c.apps.googleusercontent.com',
    iosBundleId: 'com.reso.posApps',
  );
}
